name: elixir

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: [23]
        elixir: [1.11]
    env:
      MIX_ENV: test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Branch-Name
        uses: nelonoel/branch-name@v1.0.1

      - name: Setup Elixir
        uses: actions/setup-elixir@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
          experimental-otp: true

      - name: Deps Cache
        uses: actions/cache@v1
        id: deps-cache
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Build Cache
        uses: actions/cache@v1
        id: build-cache
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Build and test
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get
          mix test

      - name: Build and test cli
        run: |
          mix escript.build
          ./hex-name -v

      - name: Check format
        run: mix format --check-formatted
